// priority: 0

// https://kubejs.com/wiki/global-scope
global.items = {
  remove: [
    "wooden_sword",
    "wooden_shovel",
    "wooden_pickaxe",
    "wooden_axe",
    "wooden_hoe",
    "stone_sword",
    "stone_shovel",
    "stone_pickaxe",
    "stone_axe",
    "stone_hoe",

    "all_the_flint_tools:flintshears",
    "all_the_flint_tools:flintaxe",
    "all_the_flint_tools:flintpickaxe",

    "aquaculture:wooden_fillet_knife",
    "aquaculture:stone_fillet_knife",

    "bettercopper:copper_helmet",
    "bettercopper:copper_chestplate",
    "bettercopper:copper_leggings",
    "bettercopper:copper_boots",
    "bettercopper:copper_heart",
    "bettercopper:copper_nugget",
    
    "natprog:quark_limestone_pebble",
    "natprog:quark_marble_pebble",
    "natprog:quark_basalt_pebble",
    "natprog:quark_slate_pebble",
    "natprog:bone_knife",
    "natprog:bronze_saw", // No bronze in the pack
    "natprog:steel_saw",  // No steel in the pack

    "sewingkit:sewing_station",
    "sewingkit:wood_sewing_needle",
    "sewingkit:stone_sewing_needle",
    "sewingkit:gold_sewing_needle",
    "sewingkit:diamond_sewing_needle",
    "sewingkit:netherite_sewing_needle",

    "ftbquests:loot_crate_opener",

    "paraglider:deku_leaf",
    "paraglider:heart_container",
    "paraglider:stamina_vessel",
    "paraglider:spirit_orb",
    "paraglider:anti_vessel",
    "paraglider:essence",
    "paraglider:goddess_statue",
    "paraglider:kakariko_goddess_statue",
    "paraglider:goron_goddess_statue",
    "paraglider:rito_goddess_statue",
    "paraglider:horned_statue",

    "quark:ravager_hide",
    "quark:bonded_ravager_hide",
    "quark:limestone",
    "quark:polished_limestone",
    "quark:limestone_bricks",
    "quark:limestone_pillar",
    "quark:limestone_slab",
    "quark:limestone_stairs",
    "quark:limestone_vertical_slab",
    "quark:limestone_wall",
    "quark:polished_limestone_slab",
    "quark:polished_limestone_stairs",
    "quark:polished_limestone_vertical_slab",
    "quark:chiseled_limestone_bricks",
    "quark:limestone_bricks_slab",
    "quark:limestone_bricks_stairs",
    "quark:limestone_bricks_vertical_slab",
    "quark:limestone_bricks_wall",

    "storagedrawers:upgrade_template",
    "storagedrawers:illumination_upgrade",
    "storagedrawers:fill_level_upgrade",
    "storagedrawers:void_upgrade",
    "storagedrawers:max_redstone_upgrade",
    "storagedrawers:min_redstone_upgrade",
    "storagedrawers:redstone_upgrade",
    "storagedrawers:creative_vending_upgrade",
    "storagedrawers:creative_storage_upgrade",
    "storagedrawers:one_stack_upgrade",
    "storagedrawers:emerald_storage_upgrade",
    "storagedrawers:diamond_storage_upgrade",
    "storagedrawers:obsidian_storage_upgrade",
    "storagedrawers:iron_storage_upgrade",
    "storagedrawers:gold_storage_upgrade",

    "domum_ornamentum:brown_bricks",
    "domum_ornamentum:beige_bricks",
    "domum_ornamentum:cream_bricks",
    "domum_ornamentum:roan_bricks",
    "domum_ornamentum:sand_bricks",
    "domum_ornamentum:brown_stone_bricks",
    "domum_ornamentum:beige_stone_bricks",
    "domum_ornamentum:cream_stone_bricks",
    "domum_ornamentum:sand_stone_bricks",
    "domum_ornamentum:roan_stone_bricks",

    "domum_ornamentum:brick_extra",
    "domum_ornamentum:black_brick_extra",
    "domum_ornamentum:blue_brick_extra",
    "domum_ornamentum:brown_brick_extra",
    "domum_ornamentum:cyan_brick_extra",
    "domum_ornamentum:gray_brick_extra",
    "domum_ornamentum:green_brick_extra",
    "domum_ornamentum:light_blue_brick_extra",
    "domum_ornamentum:light_gray_brick_extra",
    "domum_ornamentum:lime_brick_extra",
    "domum_ornamentum:magenta_brick_extra",
    "domum_ornamentum:orange_brick_extra",
    "domum_ornamentum:pink_brick_extra",
    "domum_ornamentum:purple_brick_extra",
    "domum_ornamentum:red_brick_extra",
    "domum_ornamentum:white_brick_extra",
    "domum_ornamentum:yellow_brick_extra",

    "domum_ornamentum:black_floating_carpet",
    "domum_ornamentum:blue_floating_carpet",
    "domum_ornamentum:brown_floating_carpet",
    "domum_ornamentum:cyan_floating_carpet",
    "domum_ornamentum:gray_floating_carpet",
    "domum_ornamentum:green_floating_carpet",
    "domum_ornamentum:light_blue_floating_carpet",
    "domum_ornamentum:light_gray_floating_carpet",
    "domum_ornamentum:lime_floating_carpet",
    "domum_ornamentum:magenta_floating_carpet",
    "domum_ornamentum:orange_floating_carpet",
    "domum_ornamentum:pink_floating_carpet",
    "domum_ornamentum:purple_floating_carpet",
    "domum_ornamentum:red_floating_carpet",
    "domum_ornamentum:white_floating_carpet",
    "domum_ornamentum:yellow_floating_carpet",

    "domum_ornamentum:cobblestone_extra",
    "domum_ornamentum:blue_cobblestone_extra",
    "domum_ornamentum:green_cobblestone_extra",
    "domum_ornamentum:mossy_cobblestone_extra",
    "domum_ornamentum:purple_cobblestone_extra",

    "domum_ornamentum:wheat_extra",
    "domum_ornamentum:blockbarreldeco_standing",
    "domum_ornamentum:blockbarreldeco_onside",

    "simplemagnets:basic_demagnetization_coil",
    "simplemagnets:advanced_demagnetization_coil",
  ],
  planks: {
    minecraft: [
      "oak",
      "spruce",
      "birch",
      "jungle",
      "acacia",
      "cherry",
      "dark_oak",
      "mangrove",
      // "bamboo", // wants special ratios
      // "crimson", // mushroom blocks
      // "warped", // mushroom blocks
    ],
    aquaculture: [
      "driftwood" // special blocks, oak planks
    ],
    quark: [
      "ancient",
      "azalea",
      "blossom"
    ]
  }
}

global.colors = [
  "white",
  "light_gray",
  "gray",
  "black",
  "brown",
  "red",
  "orange",
  "yellow",
  "lime",
  "green",
  "cyan",
  "light_blue",
  "blue",
  "purple",
  "magenta",
  "pink",
]
