name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eaed294fbc17402e6945ef1cd3e9287201d0aae4b45a5289d095bfa6a2f36f4d"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
