name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84be930b58395550b12a5ed6f8228bd494ee2b7af7fb6f8dca04f9084e8a4ec0"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"

[options]
datapack-folder = "./config/openloader"
