name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84886c700af5796e398d434ee6815fbfa09921b59b31333e32fad77a5935130b"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
