name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79913d911f8877a1202d0bec674ca2f6a0448e743d3f5c67b720576dff5de6b1"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
