name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c643fed13cb124ec584cf3fc15c201206dcd50c7aea05e38480e16b1e1da1e1"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
