name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f553c6be54c76a40f3eb5de42abdc048a6b5f9474e8cdc29c4f91287dceefb49"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
