name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7a4827ede3d5c197b599d0dc182ce9a5d1daeaa1c508d8434af67bede64f2c6"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
neoforge = "47.2.21"

[options]
datapack-folder = "./config/openloader"
