name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f5461b9a9fa7bf0ceea2ade57dc7a137ba15990ac5fac4910e1e7cccf4f1bcf"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
