name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5037e0e1ceaa652447bf4cad5a2b976047deb80264c475dcf96d6241b99fb4bd"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"

[options]
datapack-folder = "./config/openloader"
