name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2282e4f5a2a98507e52b6475fcc98610c77518ca95a28c8d963eeb24ae502e43"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
neoforge = "47.2.21"

[options]
datapack-folder = "./config/openloader"
