name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "785448d2330c795dc72507302c33d1af671fb3dc84d00e589b5c8f65b4000e84"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
