name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d098960ce0d9f51b10b2f52d86fcec0f5795c004fbff68341fdb8c49836e77e"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"

[options]
datapack-folder = "./config/openloader"
