name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b840c5e478bbaca29f2bc6c5f6b4e020a1fd8c7c3d0a391e141f3db6c15de6a"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
