name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e6077b2ab959703e5e47ffd3e569712558cdc87b2a2ed761863f3e2decd1ad1"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
