name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4af3843fba7d08854476cb733899380bb2e2da33501a35445f0ad5740d67afe8"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"

[options]
datapack-folder = "./config/openloader"
