name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef1dd046473329085a949b5f8ac0d245d757bfc0cb9a94e9a4853585375089ea"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"

[options]
datapack-folder = "./config/openloader"
