name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16ba114a9d8078ed677f0bf9ac6d8e38bf0848b42fc49cd34a1934dab8dcd13f"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
