name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ceec5b3381f0d9e2aa27e3746b1b18267ff5c35a550e95d97eba9a4197c9805b"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
