name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96d619205af47b7abfc8d9e5041467fc846d544376d7209aafda1d524f170b93"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
