name = "Outlander"
author = "pskfyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b2c8c8ea5f2b09016301e8b19c10f06cc1ce41385b369353df1ca17e82d09f7"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
