
[blocks]
	Kiln = false
	"Chiseled bricks" = false
	"Glazed terracotta" = false
	"Terracotta slabs, stairs, and walls" = false
	"Terracotta bricks" = false

	[blocks.decorated_pot]
		"Decorated pot colors" = false
		"Decorated pot trims" = false

